Code review: Project 2: Members Only!
simoxsimo/members-only pull request #1
Opened 2020-03-12 17:15 UTC by bafiam

#### What does this PR do?
1. Consist of the member only project
#### How should this be manually tested?
Clone the repo then navigate to the project directory, follow the instruction on the readme

2020-03-13 03:42 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,
Thank you for the simplicity of your work.
To move forward, you need some changes to do

1. Please, forget about using `session` in this project. Only think about using `cookies.permanent`. 
The `remember_me token` the project describes consists of storing a hash in a cookie and using it to determine in a user is logged in. Do not confuse it with the Remember me \[ \] checkbox that many websites show. That is a more complex solution, which is **not required** here.

2. You forgot to define the method to set user `#current_user=(user)`  as indicated in that [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/current_user_requirement.png)

3. In your remember token, you forgot to set the current user, to update the current user with his remember token.

4. In the `http://localhost:3000`, `Sign up now!` is not working, no link there! I was obliged to create a user through `rails console`

5. Read the comment below.

Kindly make the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

2020-03-13 03:42 UTC, maelfosso commented on app/controllers/sessions_controller.rb
> +      session[:user_id] = user.id
Forget about using `session`, please.

2020-03-13 03:42 UTC, maelfosso commented on app/controllers/application_controller.rb
> +  end
Too long. Rewrite it by keeping in my that when a user is connected only the remember token is set up in cookies.permanent.

2020-03-13 03:42 UTC, maelfosso commented on app/controllers/application_controller.rb
> +    session.delete(:user_id)
No needed

2020-03-16 19:46 UTC, simoxsimo commented
## Problems are fixed !!

2020-03-16 23:59 UTC, maelfosso approved these changes
# Congratulations :clap: 

You can merge it :+1: 
Good luck with the next :handshake: 

Mael FOSSO

2020-03-17 10:47 UTC, merged